librdkafka: install 9.1
behance/docker-php pull request #123
Opened 2017-02-08 19:06 UTC by mikeklein13

2017-02-08 19:45 UTC, bossjones commented
simple change ... but needs a test. I'd check to ensure the sources file gets created correctly. should be located in `/etc/apt/sources.d` something like that. File contents should look like:

```
deb http://ppa.launchpad.net/guessi/librdkafka/ubuntu xenial main 
deb-src http://ppa.launchpad.net/guessi/librdkafka/ubuntu xenial main 
```

Also, I'm assuming alpine is already installing the latest version of libkafka and thats why you didn't need a modification to it?

2017-02-09 07:27 UTC, bryanlatten commented
@mikeklein13 agreed with @bossjones, would love to see a version test if possible.

2017-02-14 21:56 UTC, bossjones commented
👍

2017-02-14 22:09 UTC, bryanlatten requested changes

2017-02-14 22:09 UTC, bryanlatten commented on container/root/tests/php-fpm/beta.goss.yaml
> +      - "0.9.1-1ppa1~xenial"
if this version gets updated, its going to break any further builds. Can you do a substring to just look for `0.9.1` instead?

2017-02-15 16:20 UTC, bryanlatten approved these changes

2017-02-15 16:20 UTC, merged